emfox_gps_index:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /main/google
        permanent: true
emfox_gps_main:
    path:     /main/{maptype}
    defaults: { _controller: "EmfoxGpsBundle:Default:main", maptype: "google" }
emfox_gps_proxy:
    path:     /proxy/{url}
    defaults: { _controller: "EmfoxGpsBundle:Default:proxy" }
    requirements:
      url: .+
emfox_gps_category:
    resource: "@EmfoxGpsBundle/Controller/CategoryController.php"
    type: annotation
    prefix:   /
emfox_gps_anchor:
    resource: "@EmfoxGpsBundle/Controller/AnchorController.php"
    type: annotation
    prefix:   /
emfox_gps_trail:
    resource: "@EmfoxGpsBundle/Controller/TrailController.php"
    type: annotation
    prefix:   /
emfox_gps_message:
    resource: "@EmfoxGpsBundle/Controller/MessageController.php"
    type: annotation
    prefix:   /
emfox_gps_user:
    resource: "@EmfoxGpsBundle/Controller/UserController.php"
    type: annotation
    prefix:   /
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"