emfox_gps_homepage:
    path:     /
    defaults: { _controller: "EmfoxGpsBundle:Default:index" }
emfox_gps_proxy:
    path:     /proxy/{url}
    defaults: { _controller: "EmfoxGpsBundle:Default:proxy" }
    requirements:
      url: .+
emfox_gps_category:
    resource: "@EmfoxGpsBundle/Controller/CategoryController.php"
    type: annotation
    prefix:   /
    
emfox_gps_trail:
    resource: "@EmfoxGpsBundle/Controller/TrailController.php"
    type: annotation
    prefix:   /
    
emfox_gps_user:
    resource: "@EmfoxGpsBundle/Controller/UserController.php"
    type: annotation
    prefix:   /
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"