emfox_gps_homepage:
    path:     /
    defaults: { _controller: "EmfoxGpsBundle:Default:index" }

emfox_gps_category:
    resource: "@EmfoxGpsBundle/Controller/CategoryController.php"
    type: annotation
    prefix:   /