parameters:
#    emfox_gps.example.class: Emfox\GpsBundle\Example

services:
#    emfox_gps.example:
#        class: %emfox_gps.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
