security:
    encoders:
        App\Entity\User:
            algorithm: auto


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
            anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, role: ROLE_ADMIN }
        - { path: ^/category/hierarchy, role: ROLE_USER }
        - { path: ^/category/, role: ROLE_ADMIN }
        - { path: ^/anchor/list, role: ROLE_USER }
        - { path: ^/anchor/, role: ROLE_ADMIN }
        - { path: ^/trail/new, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/trail/, role: ROLE_USER }
        - { path: ^/message/send, role: ROLE_USER }
        - { path: ^/message, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY } #unprotect dev-toolbar so to redirect to right page.
        - { path: ^/main, role: ROLE_USER }
        - { path: ^/, role: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
