emfox_gps_index:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /main/google
        permanent: true
emfox_gps_main:
    path:     /main/{maptype}
    defaults:
        _controller: "App\\Controller\\DefaultController::mainAction"
        maptype: "google"
